typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 4>::Type Poly4;
typedef CGAL::Polynomial_traits_d<Poly4>                     PT4;
typedef std::pair<CGAL::Exponent_vector, PT4::Innermost_coefficient_type> Monomial4;
typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 5>::Type Poly5;
typedef CGAL::Polynomial_traits_d<Poly5>                     PT5;
typedef std::pair<CGAL::Exponent_vector, PT5::Innermost_coefficient_type> Monomial5;
typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 6>::Type Poly6;
typedef CGAL::Polynomial_traits_d<Poly6>                     PT6;
typedef std::pair<CGAL::Exponent_vector, PT6::Innermost_coefficient_type> Monomial6;
typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 7>::Type Poly7;
typedef CGAL::Polynomial_traits_d<Poly7>                     PT7;
typedef std::pair<CGAL::Exponent_vector, PT7::Innermost_coefficient_type> Monomial7;
typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 8>::Type Poly8;
typedef CGAL::Polynomial_traits_d<Poly8>                     PT8;
typedef std::pair<CGAL::Exponent_vector, PT8::Innermost_coefficient_type> Monomial8;
typedef CGAL::Polynomial_type_generator<CGAL::Gmpq, 9>::Type Poly9;
typedef CGAL::Polynomial_traits_d<Poly9>                     PT9;
typedef std::pair<CGAL::Exponent_vector, PT9::Innermost_coefficient_type> Monomial9;
