# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resultantCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_resultantCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

resultantCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permute) {
    .Call(`_resultant_resultantCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, permute)
}

resultantCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_principalSubresultantsCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

principalSubresultantsCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permute) {
    .Call(`_resultant_principalSubresultantsCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, permute)
}

principalSubresultantsCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

principalSubresultantsCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_principalSubresultantsCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

gcdCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP1`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

numberOfRealRootsCPP <- function(Powers, Coeffs) {
    .Call(`_resultant_numberOfRealRootsCPP`, Powers, Coeffs)
}

divModCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_divModCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

integralDivisionCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP1`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

SturmHabichtCPP1 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP1`, Powers, Coeffs)
}

SturmHabichtCPP2 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP2`, Powers, Coeffs)
}

SturmHabichtCPP3 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP3`, Powers, Coeffs)
}

SturmHabichtCPP4 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP4`, Powers, Coeffs)
}

SturmHabichtCPP5 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP5`, Powers, Coeffs)
}

SturmHabichtCPP6 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP6`, Powers, Coeffs)
}

SturmHabichtCPP7 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP7`, Powers, Coeffs)
}

SturmHabichtCPP8 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP8`, Powers, Coeffs)
}

SturmHabichtCPP9 <- function(Powers, Coeffs) {
    .Call(`_resultant_SturmHabichtCPP9`, Powers, Coeffs)
}

principalSturmHabichtCPP1 <- function(Powers, Coeffs) {
    .Call(`_resultant_principalSturmHabichtCPP1`, Powers, Coeffs)
}

principalSturmHabichtCPP2 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP2`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP3 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP3`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP4 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP4`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP5 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP5`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP6 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP6`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP7 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP7`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP8 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP8`, Powers, Coeffs, permutation)
}

principalSturmHabichtCPP9 <- function(Powers, Coeffs, permutation) {
    .Call(`_resultant_principalSturmHabichtCPP9`, Powers, Coeffs, permutation)
}

