# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resultantCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_resultantCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

resultantCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permute) {
    .Call(`_resultant_resultantCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, permute)
}

resultantCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

resultantCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_resultantCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_subresultantsCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

subresultantsCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permute) {
    .Call(`_resultant_subresultantsCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, permute)
}

subresultantsCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

subresultantsCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, permutation) {
    .Call(`_resultant_subresultantsCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, permutation)
}

gcdCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP1`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

gcdCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, UTCF) {
    .Call(`_resultant_gcdCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, UTCF)
}

numberOfRealRootsCPP <- function(Powers, Coeffs) {
    .Call(`_resultant_numberOfRealRootsCPP`, Powers, Coeffs)
}

divModCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG) {
    .Call(`_resultant_divModCPP1`, PowersF, CoeffsF, PowersG, CoeffsG)
}

integralDivisionCPP1 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP1`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP2 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP2`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP3 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP3`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP4 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP4`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP5 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP5`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP6 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP6`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP7 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP7`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP8 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP8`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

integralDivisionCPP9 <- function(PowersF, CoeffsF, PowersG, CoeffsG, check) {
    .Call(`_resultant_integralDivisionCPP9`, PowersF, CoeffsF, PowersG, CoeffsG, check)
}

